# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Diner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(verbose_name='Dish Description')),
                ('default_serving_size', models.IntegerField(default=1)),
                ('cuisine_tags', models.ManyToManyField(to='dishes.CuisineTag')),
            ],
        ),
        migrations.CreateModel(
            name='DishPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_servings', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('serving_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('last_call', models.DateTimeField(verbose_name='Last Call')),
                ('meal_time', models.DateTimeField(verbose_name='Meal Time')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Cancelled'), (3, 'Complete')])),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Chef')),
                ('diners', models.ManyToManyField(to='dishes.Diner')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_servings', models.IntegerField(default=1)),
                ('diner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Diner')),
                ('dish_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.DishPost')),
            ],
        ),
    ]
