# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20161115_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishpost',
            name='diners',
        ),
        migrations.AlterField(
            model_name='cuisinetag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='dishpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Cancelled'), (3, 'Complete')], default=0),
        ),
    ]
