# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 00:39
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20161115_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='serving_size',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=3),
        ),
    ]
