# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 00:00
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Complaint Description')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Closed')], default=0)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_allegation', to=settings.AUTH_USER_MODEL)),
                ('complainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_receipt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Closed')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chefpermissionsrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='createaccountrequest',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='createaccountrequest',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='createaccountrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='createaccountrequest',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='createaccountrequest',
            name='username',
            field=models.CharField(default='0', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chefpermissionsrequest',
            name='first_dish_image',
            field=models.ImageField(max_length=256, upload_to='chef-permissions-requests-uploads/'),
        ),
        migrations.AlterField(
            model_name='chefpermissionsrequest',
            name='second_dish_image',
            field=models.ImageField(max_length=256, upload_to='chef-permissions-requests-uploads/'),
        ),
        migrations.AlterField(
            model_name='chefpermissionsrequest',
            name='third_dish_image',
            field=models.ImageField(max_length=256, upload_to='chef-permissions-requests-uploads/'),
        ),
        migrations.AlterField(
            model_name='chefpermissionsrequest',
            name='video_biography',
            field=models.FileField(max_length=256, upload_to='chef-permissions-requests-uploads/'),
        ),
        migrations.AlterField(
            model_name='createaccountrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
