# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 03:52
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_auto_20161208_0352'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20161207_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=11)),
                ('is_vip', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to='dishes.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='struck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redflag',
            name='reason',
            field=models.IntegerField(choices=[(0, 'User has given 3 lowest ratings and 3 complaints.'), (1, 'User has given 5 highest ratings in the last 5 transactions.')], default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_allegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
