# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20161208_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveSuspensionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='redflag',
            name='reason',
            field=models.IntegerField(choices=[(0, 'User has given 3 lowest ratings and 3 complaints.'), (1, 'User has given 5 highest ratings in the last 5 transactions.')], default=0),
        ),
    ]
