# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20161210_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflag',
            name='reason',
            field=models.IntegerField(choices=[(0, 'User has given 3 lowest ratings and 3 complaints.'), (1, 'User has given 5 highest ratings in the last 5 transactions.')], default=1),
        ),
    ]
