# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_removesuspensionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='removesuspensionrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='RemoveSuspensionRequest',
        ),
    ]
