# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='default_serving_size',
        ),
        migrations.AddField(
            model_name='dish',
            name='serving_size',
            field=models.DecimalField(decimal_places=1, default=4.99, max_digits=3),
        ),
    ]
