# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20161116_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('num_servings', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('meal_time', models.DateTimeField(verbose_name='Meal Time')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Cancelled'), (3, 'Complete')], default=0)),
                ('diner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Diner')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.Dish')),
            ],
        ),
    ]
