# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 17:21
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_dishrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RateChef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='RateDiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AddField(
            model_name='chef',
            name='blurb',
            field=models.TextField(default='I cook for a living', verbose_name='Blurb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='experience',
            field=models.TextField(default="I'v always cooked for a living", verbose_name='Experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='followers',
            field=models.ManyToManyField(related_name='followees', to='dishes.Diner'),
        ),
        migrations.AddField(
            model_name='chef',
            name='name',
            field=models.CharField(default='Ben John', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diner',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='diner',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='dish',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='dish',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='dishpost',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='dishpost',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='dishrequest',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='dishrequest',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Cancelled'), (2, 'Complete')], default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dishpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Cancelled'), (2, 'Complete')], default=0),
        ),
        migrations.AlterField(
            model_name='dishrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Cancelled'), (2, 'Complete')], default=0),
        ),
        migrations.AddField(
            model_name='ratediner',
            name='diner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Chef'),
        ),
        migrations.AddField(
            model_name='ratechef',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Chef'),
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Order'),
        ),
    ]
