# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 03:52
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0006_auto_20161206_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('struck', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ratee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderfeedback',
            name='title',
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Pending Feedback'), (2, 'Cancelled'), (3, 'Complete')], default=0),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Order'),
        ),
    ]
