# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_auto_20161208_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='alchemy_label',
            field=models.TextField(null=True),
        ),
    ]
