# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_auto_20161210_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratechef',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratediner',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
