# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0015_auto_20161210_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_servings', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('diner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Diner')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Chef')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='alchemy_label',
        ),
        migrations.RemoveField(
            model_name='dishpost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dishrequest',
            name='price',
        ),
        migrations.AddField(
            model_name='dishpost',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Minimum Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishrequest',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Minimum Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='chef_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='diner_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dishpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Pending Feedback'), (2, 'Cancelled'), (3, 'Complete')], default=0),
        ),
        migrations.AlterField(
            model_name='dishrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Accepted'), (2, 'Cancelled'), (3, 'Complete')], default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='dish_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.DishRequest'),
        ),
        migrations.AddField(
            model_name='bid',
            name='dish_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.DishPost'),
        ),
        migrations.AddField(
            model_name='order',
            name='bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dishes.Bid'),
            preserve_default=False,
        ),
    ]
